spring:
    application:
        name: FirstPracticeProject

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                default_schema: second_practice
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect